### ISSUE TITLE
ImportError: cannot import name 'Deque'

### ISSUE THREAD

**Issue by takearest118** [takearest118/lambor#1]
somebody help me
my development environment is python 3.6 on macOS

```
(lambor) vlab008ui-MacBook-Pro:lambor vlab008$ python app.py
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from sanic import Sanic
  File "/Users/vlab008/workspaces/venv/lambor/lib/python3.6/site-packages/sanic/__init__.py", line 2, in <module>
    from sanic.app import Sanic
  File "/Users/vlab008/workspaces/venv/lambor/lib/python3.6/site-packages/sanic/app.py", line 18, in <module>
    from sanic.asgi import ASGIApp
  File "/Users/vlab008/workspaces/venv/lambor/lib/python3.6/site-packages/sanic/asgi.py", line 28, in <module>
    from sanic.websocket import WebSocketConnection
  File "/Users/vlab008/workspaces/venv/lambor/lib/python3.6/site-packages/sanic/websocket.py", line 12, in <module>
    from websockets import (  # type: ignore
  File "/Users/vlab008/workspaces/venv/lambor/lib/python3.6/site-packages/websockets/__init__.py", line 3, in <module>
    from .auth import *
  File "/Users/vlab008/workspaces/venv/lambor/lib/python3.6/site-packages/websockets/auth.py", line 15, in <module>
    from .server import HTTPResponse, WebSocketServerProtocol
  File "/Users/vlab008/workspaces/venv/lambor/lib/python3.6/site-packages/websockets/server.py", line 49, in <module>
    from .protocol import WebSocketCommonProtocol
  File "/Users/vlab008/workspaces/venv/lambor/lib/python3.6/site-packages/websockets/protocol.py", line 18, in <module>
    from typing import (
ImportError: cannot import name 'Deque'

```

**Comment by takearest118** [comment]
> somebody help me
> my development environment is python 3.6 on macOS
> 
> ```
> (lambor) vlab008ui-MacBook-Pro:lambor vlab008$ python app.py
> Traceback (most recent call last):
>   File "app.py", line 3, in <module>
>     from sanic import Sanic
>   File "/Users/vlab008/workspaces/venv/lambor/lib/python3.6/site-packages/sanic/__init__.py", line 2, in <module>
>     from sanic.app import Sanic
>   File "/Users/vlab008/workspaces/venv/lambor/lib/python3.6/site-packages/sanic/app.py", line 18, in <module>
>     from sanic.asgi import ASGIApp
>   File "/Users/vlab008/workspaces/venv/lambor/lib/python3.6/site-packages/sanic/asgi.py", line 28, in <module>
>     from sanic.websocket import WebSocketConnection
>   File "/Users/vlab008/workspaces/venv/lambor/lib/python3.6/site-packages/sanic/websocket.py", line 12, in <module>
>     from websockets import (  # type: ignore
>   File "/Users/vlab008/workspaces/venv/lambor/lib/python3.6/site-packages/websockets/__init__.py", line 3, in <module>
>     from .auth import *
>   File "/Users/vlab008/workspaces/venv/lambor/lib/python3.6/site-packages/websockets/auth.py", line 15, in <module>
>     from .server import HTTPResponse, WebSocketServerProtocol
>   File "/Users/vlab008/workspaces/venv/lambor/lib/python3.6/site-packages/websockets/server.py", line 49, in <module>
>     from .protocol import WebSocketCommonProtocol
>   File "/Users/vlab008/workspaces/venv/lambor/lib/python3.6/site-packages/websockets/protocol.py", line 18, in <module>
>     from typing import (
> ImportError: cannot import name 'Deque'
> ```

Fix install Python 3.6.8
